#
# GITLAB CI/CD INSTRUCTIONS
#

stages:
  - "build-push-docker-image"
  - "create-release"

build-push-docker-image:
  image: "docker:latest"
  stage: "build-push-docker-image"
  services: ["docker:dind"]
  script: ["/bin/sh ${CI_PROJECT_DIR}/gitlab/build-push-docker-image.sh"]
  rules: ["$CI_COMMIT_TAG =~ /^[0-9]{10}$/"]

create-release:
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  stage: "create-release"
  script: ["exit 0"]
  release:
    name: "$CI_COMMIT_TAG"
    description: "Created with CI/CD"
    tag_name: "$CI_COMMIT_TAG"
  rules: ["$CI_COMMIT_TAG =~ /^[0-9]{10}$/"]
