#
# ##########
# BASE IMAGE
# ##########
#

FROM registry.ans.co.at/templates/nndocs/nndocs:latest

#
# #################
# IMAGE INFORMATION
# #################
#

ARG IMAGE_VERSION=2.0.0
ARG IMAGE_BUILD_DATE=0000000000

ENV MKPDF_VERSION="V${IMAGE_VERSION}"
ENV MKPDF_BUILD_DATE="B${IMAGE_BUILD_DATE}"
ENV MKPDF_IMAGE_MAINTAINER='Norbert EHART (norbert@ehart.net)'

#
# #####################
# ENVIRONMENT VARIABLES
# #####################
#

ENV HOME="/tmp/"

#
# ##############
# CONTAINER USER
# ##############
#

USER 0:0

#
# ########
# TEMPLATE
# ########
#

COPY mkbase.yml /usr/local/share/mmdocs-tmpl/mkbase.yml
COPY mkdocs.yml /usr/local/share/mmdocs-tmpl/mkdocs.yml

RUN rm -rf /usr/local/share/mmdocs-tmpl/.gitlab-ci.yml
RUN rm -rf /usr/local/share/mmdocs-tmpl/.gitignore
RUN rm -rf /usr/local/share/mmdocs-tmpl/mkpdf.yml

COPY pages/index.md /usr/local/share/mmdocs-tmpl/pages/index.md
COPY pages/images/cover.png /usr/local/share/mmdocs-tmpl/pages/images/cover.png

COPY overrides_pdf/cover.scss /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/styles/cover.scss
COPY overrides_pdf/fonts.scss /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/styles/_fonts.scss
COPY overrides_pdf/heading.scss /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/styles/_heading.scss
COPY overrides_pdf/paging.scss /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/styles/_paging.scss
COPY overrides_pdf/toc.scss /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/styles/_toc.scss

COPY overrides_pdf/cover.html.j2 /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/templates/default_cover.html.j2
COPY overrides_pdf/back_cover.html.j2 /usr/local/lib/python3.12/site-packages/mkdocs_with_pdf/templates/default_back_cover.html.j2

COPY overrides_mkdocs/ /usr/local/lib/python3.12/site-packages/material/templates/

#
# ################
# ENTRYPOINT & CMD
# ################
#

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD [""]

#
# #######
# WORKDIR
# #######
#

WORKDIR /mnt/